import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Stream me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-2xl text-red-500 bg-black">hello world</div>
    </div>
  );
}
